spring:
  application:
    name: service-c
  profiles:
    active:
    - instance2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  config:
    activate:
      on-profile: instance1
server:
  port: 8082
eureka:
  instance:
    instance-id: service-c:8082

---
spring:
  config:
    activate:
      on-profile: instance2
server:
  port: 8083
eureka:
  instance:
    instance-id: service-c:8083

